### ISSUE TITLE
404 hasznalata kellene

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#32]
Ha hívunk egy oldalt, ami nincs, akkor redirect az index.html-re történik.
Szerintem ez antipattern.
Jobb lenne 404.
Jó példa:
https://google.com/nincs_ilyen_oldal
Rossz példa:
http://kaputelefon.local/nincs_ilyen_oldal

**Comment by boborjan2** [comment]
"Since Android 5.0 (API level 21), Android devices have detected captive portals and notified the user that they need to sign in to the network to access the internet. Captive portals were detected using cleartext HTTP probes to known destinations (such as connectivitycheck.gstatic.com), and if the probe received an HTTP redirect, the device assumed that the network was a captive portal. "
https://developer.android.com/about/versions/11/features/captive-portal

**Comment by boborjan2** [comment]
kurrens iphone:https://developer.apple.com/news/?id=q78sq5rv

mindketto adoptalta ezt:
https://datatracker.ietf.org/doc/html/draft-ietf-capport-rfc7710bis

DHCP server elmondja, mi a captive portal es kesz. A regi keszulekek meg majd kikopnak :)

Ezt tudjuk tamogatni.

**Comment by boborjan2** [comment]
0.1.15: ebben mar csak ott van 302 redirect, ahol szukseges (tehat az AP-t celzo requestek eseten, amennyiben a dns capture engedelyezve van)
